# Generated by Django 2.1.1 on 2018-11-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='用例名称')),
                ('url', models.TextField(default='', verbose_name='url地址')),
                ('method', models.CharField(default='get', max_length=10, verbose_name='请求方法')),
                ('datatpye', models.CharField(default='form', max_length=10, verbose_name='参数形式')),
                ('headers', models.TextField(default='', verbose_name='请求header')),
                ('params', models.TextField(default='', verbose_name='请求参数')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
