# Generated by Django 2.1 on 2018-11-30 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_app', '0002_auto_20181115_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=50, verbose_name='所属项目')),
                ('name', models.CharField(default='', max_length=100, verbose_name='用例名称')),
                ('url', models.TextField(default='', verbose_name='url地址')),
                ('method', models.CharField(default='get', max_length=10, verbose_name='请求方法')),
                ('datatpye', models.CharField(default='form', max_length=10, verbose_name='参数形式')),
                ('headers', models.TextField(default='', verbose_name='请求header')),
                ('params', models.TextField(default='', verbose_name='请求参数')),
                ('result', models.TextField(default='', verbose_name='返回结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.module')),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='任务名称')),
                ('describe', models.TextField(default='', verbose_name='任务描述')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('cases', models.TextField(default='', verbose_name='包含用例')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
